apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox-test
    image: busybox:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10; done"]