apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      containers:
      - name: fluentd-k8s-test
        image: fluent/fluentd:edge-debian
        imagePullPolicy: "IfNotPresent"
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
        volumeMounts:
        - name: varlog
          mountPath: /tmp/log
      
      volumes:
      - name: varlog
        hostPath: 
          path: /tmp/log  




